<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>Vb6ToCSharp.ConsoleApp</RootNamespace>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <Copyright>Copyright (c) Piero Viano 2026. All rights reserved.</Copyright>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Vb6ToCSharp.Library\Vb6ToCSharp.Library.csproj" />
    </ItemGroup>
</Project>
