<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ProcessForGtk</RootNamespace>
        <Nullable>enable</Nullable>
        <Copyright>Copyright (c) Piero Viano 2026. All rights reserved.</Copyright>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
</Project>
