using static Microsoft.VisualBasic.Constants;
using static Vb6ToCSharp.Modules.ModConvert;


namespace Vb6ToCSharp.Modules;

public static class FormTest
{
    // Option Explicit


    public static string TestCase()
    {
        var a = "";
        var m = "";
        var n = vbCrLf;

        a = a + m + "Public Function ReadEntireFile(ByVal tFileName As String) As String";
        a = a + n + "'::::ReadEntireFile";
        a = a + n + "':::SUMMARY";
        a = a + n + "':Read an entire file.";
        a = a + n + "':::DESCRIPTION";
        a = a + n + "':Reads  the full contents of a file and returns the value as a string (without modification).";
        a = a + n + "':::PARAMETERS";
        a = a + n + "':- tFileName - The name of the file to read.";
        a = a + n + "':::RETURN";
        a = a + n + "':  String - The string contents of the file.";
        a = a + n + "':::SEE ALSO";
        a = a + n + "':  ReadFile, WriteFile, ReadEntireFileAndDelete";
        a = a + n + "";
        a = a + n + "On Error Resume Next";
        a = a + n + "  With CreateObject(\"Scripting.FileSystemObject\")";
        a = a + n + "    ReadEntireFile = .OpenTextFile(tFileName, 1).ReadAll";
        a = a + n + "  End With";
        a = a + n + "  ";
        a = a + n + "  If FileLen(tFileName) / 10 <> Len(ReadEntireFile) / 10 Then";
        a = a + n + "    MsgBox \"ReadEntireFile was short: \" & FileLen(tFileName) & \" vs \" & Len(ReadEntireFile)";
        a = a + n + "  End If";
        a = a + n + "'";
        a = a + n + "'  Dim intFile As Long";
        a = a + n + "'  intFile = FreeFile";
        a = a + n + "'On Error Resume Next";
        a = a + n + "'  Open tFileName For Input As #intFile";
        a = a + n + "'  ReadEntireFile = Input$(LOF(intFile), #intFile)  '  LOF returns Length of File";
        a = a + n + "'  Close #intFile";
        a = a + n + "End Function";
        var testCase = a;
        return testCase;
    }

    public static string TestCase2()
    {
        var a = "";
        var n = vbCrLf;

        a = a + n + "Public Function DescribeColor(ByVal RGB As Long) As String";
        a = a + n + "  Dim R As Long, G As Long, B As Long";
        a = a + n + "  Select Case RGB";
        a = a + n + "    Case vbBlack:     DescribeColor = \"BLACK\"";
        a = a + n + "    Case vbBlue:      DescribeColor = \"BLUE\"";
        a = a + n + "    Case vbCyan:      DescribeColor = \"CYAN\"";
        a = a + n + "    Case vbGreen:     DescribeColor = \"GREEN\"";
        a = a + n + "    Case vbMagenta:   DescribeColor = \"MAGENTA\"";
        a = a + n + "    Case vbRed:       DescribeColor = \"RED\"";
        a = a + n + "    Case vbWhite:     DescribeColor = \"WHITE\"";
        a = a + n + "    Case vbYellow:    DescribeColor = \"YELLOW\"";
        a = a + n + "";
        a = a + n + "    Case Else";
        a = a + n + "      DescribeColor = \"OTHER\"";
        a = a + n + "      R = RGB And 255";
        a = a + n + "      G = (RGB And 65280) / 256";
        a = a + n + "      B = (RGB And 16711680) / 65536";
        a = a + n + "      DescribeColor = DescribeColor & \" (R:\" & R & \",G:\" & G & \",:\" & B & \")\"";
        a = a + n + "  End Select";
        a = a + n + "";
        a = a + n + " ' If SingleLineIf Then DoSomeStuff: AndMore()";
        a = a + n + "";
        a = a + n + "GotoLabel:";
        a = a + n + "  SomeFunction()";
        a = a + n + "End Function";

        var testCase2 = SanitizeCode(a);
        return testCase2;
    }

    public static string TestCaseFrm()
    {
        var s = "";

        var n = vbCrLf;
        s = s + n + "VERSION 5.00";
        s = s + n + "Begin VB.Form frmAbout ";
        s = s + n + "   BackColor       =   &H000000FF&";
        s = s + n + "   BorderStyle     =   0  'None";
        s = s + n + "   ClientHeight    =   4485";
        s = s + n + "   ClientLeft      =   0";
        s = s + n + "   ClientTop       =   0";
        s = s + n + "   ClientWidth     =   6300";
        s = s + n + "   Icon            =   \"frmAbout.frx\":0000";
        s = s + n + "   LinkTopic       =   \"Form1\"";
        s = s + n + "   ScaleHeight     =   4485";
        s = s + n + "   ScaleWidth      =   6300";
        s = s + n + "   ShowInTaskbar   =   0   'False";
        s = s + n + "   StartUpPosition =   2  'CenterScreen";
        s = s + n + "   Begin VB.Timer tmr ";
        s = s + n + "      Interval        =   150";
        s = s + n + "      Left            =   5760";
        s = s + n + "      Top             =   120";
        s = s + n + "   End";
        s = s + n + "   Begin VB.Label lblInfo ";
        s = s + n + "      Appearance      =   0  'Flat";
        s = s + n + "      BackColor       =   &H80000005&";
        s = s + n + "      BackStyle       =   0  'Transparent";
        s = s + n + "      BorderStyle     =   1  'Fixed Single";
        s = s + n + "      Caption         =   \"###\"";
        s = s + n + "      ForeColor       =   &H80000008&";
        s = s + n + "      Height          =   2175";
        s = s + n + "      Left            =   2400";
        s = s + n + "      TabIndex        =   0";
        s = s + n + "      Top             =   2160";
        s = s + n + "      Width           =   3735";
        s = s + n + "   End";
        s = s + n + "   Begin VB.Shape shpFrame ";
        s = s + n + "      BorderWidth     =   3";
        s = s + n + "      Height          =   4440";
        s = s + n + "      Left            =   15";
        s = s + n + "      Top             =   15";
        s = s + n + "      Width           =   6270";
        s = s + n + "   End";
        s = s + n + "   Begin VB.Image imgBacking ";
        s = s + n + "      Height          =   975";
        s = s + n + "      Left            =   1320";
        s = s + n + "      Stretch         =   -1  'True";
        s = s + n + "      Top             =   600";
        s = s + n + "      Width           =   1335";
        s = s + n + "   End";
        s = s + n + "End";
        s = s + n + "Attribute VB_Name = \"frmAbout\"";
        s = s + n + "Attribute VB_GlobalNameSpace = False";
        s = s + n + "Attribute VB_Creatable = False";
        s = s + n + "Attribute VB_PredeclaredId = True";
        s = s + n + "Attribute VB_Exposed = False";
        s = s + n + "";

        var testCaseFrm = s;
        return testCaseFrm;
    }

    public static string TestCaseFrm2()
    {
        var n = vbCrLf;
        var s = "";
        s = s + n + "VERSION 5.00";
        s = s + n + "Object = \"{86CF1D34-0C5F-11D2-A9FC-0000F8754DA1}#2.0#0\"; \"Mscomct2.ocx\"";
        s = s + n + "Begin VB.Form ARPaySetUp ";
        s = s + n + "   BorderStyle     =   1  'Fixed Single";
        s = s + n + "   Caption         =   \"Payment Set Up\"";
        s = s + n + "   ClientHeight    =   8820";
        s = s + n + "   ClientLeft      =   45";
        s = s + n + "   ClientTop       =   330";
        s = s + n + "   ClientWidth     =   4815";
        s = s + n + "   Icon            =   \"ArPaySetUp.frx\":0000";
        s = s + n + "   LinkTopic       =   \"Form2\"";
        s = s + n + "   MaxButton       =   0   'False";
        s = s + n + "   ScaleHeight     =   8820";
        s = s + n + "   ScaleWidth      =   4815";
        s = s + n + "   StartUpPosition =   2  'CenterScreen";
        s = s + n + "   Begin VB.PictureBox picPicture ";
        s = s + n + "      Height          =   375";
        s = s + n + "      Left            =   4080";
        s = s + n + "      ScaleHeight     =   315";
        s = s + n + "      ScaleWidth      =   375";
        s = s + n + "      TabIndex        =   70";
        s = s + n + "      Top             =   360";
        s = s + n + "      Visible         =   0   'False";
        s = s + n + "      Width           =   435";
        s = s + n + "   End";
        s = s + n + "   Begin VB.Frame fraARPaySetup ";
        s = s + n + "      BeginProperty Font ";
        s = s + n + "         Name            =   \"MS Sans Serif\"";
        s = s + n + "         Size            =   9.75";
        s = s + n + "         Charset         =   0";
        s = s + n + "         Weight          =   400";
        s = s + n + "         Underline       =   0   'False";
        s = s + n + "         Italic          =   0   'False";
        s = s + n + "         Strikethrough   =   0   'False";
        s = s + n + "      EndProperty";
        s = s + n + "      Height          =   8595";
        s = s + n + "      Left            =   120";
        s = s + n + "      TabIndex        =   68";
        s = s + n + "      Top             =   120";
        s = s + n + "      Width           =   4575";
        s = s + n + "      Begin VB.TextBox txtUnemploymentInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   35";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   4920";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkUnemployment ";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2820";
        s = s + n + "         TabIndex        =   36";
        s = s + n + "         Top             =   4920";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   255";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtTotalBalance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         Locked          =   -1  'True";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   52";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   6960";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Frame fraJointLife ";
        s = s + n + "         BorderStyle     =   0  'None";
        s = s + n + "         Height          =   495";
        s = s + n + "         Left            =   3120";
        s = s + n + "         TabIndex        =   79";
        s = s + n + "         Top             =   4200";
        s = s + n + "         Width           =   1335";
        s = s + n + "         Begin VB.OptionButton optJointLife ";
        s = s + n + "            Caption         =   \"Joint Life\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Index           =   1";
        s = s + n + "            Left            =   120";
        s = s + n + "            TabIndex        =   57";
        s = s + n + "            Top             =   240";
        s = s + n + "            Width           =   975";
        s = s + n + "         End";
        s = s + n + "         Begin VB.OptionButton optJointLife ";
        s = s + n + "            Caption         =   \"Single Life\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Index           =   0";
        s = s + n + "            Left            =   120";
        s = s + n + "            TabIndex        =   56";
        s = s + n + "            Top             =   0";
        s = s + n + "            Value           =   -1  'True";
        s = s + n + "            Width           =   1095";
        s = s + n + "         End";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Timer tmrLoad ";
        s = s + n + "         Enabled         =   0   'False";
        s = s + n + "         Interval        =   10";
        s = s + n + "         Left            =   3840";
        s = s + n + "         Top             =   960";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkRoundUp ";
        s = s + n + "         Caption         =   \"Round Up\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   1800";
        s = s + n + "         TabIndex        =   55";
        s = s + n + "         Top             =   7800";
        s = s + n + "         Value           =   1  'Checked";
        s = s + n + "         Width           =   1095";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CommandButton cmdCancel ";
        s = s + n + "         Cancel          =   -1  'True";
        s = s + n + "         Caption         =   \"&Cancel\"";
        s = s + n + "         Height          =   315";
        s = s + n + "         Left            =   3120";
        s = s + n + "         TabIndex        =   64";
        s = s + n + "         Top             =   8160";
        s = s + n + "         Width           =   1215";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CommandButton cmdApply ";
        s = s + n + "         Caption         =   \"&Apply\"";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   3720";
        s = s + n + "         TabIndex        =   63";
        s = s + n + "         Top             =   7800";
        s = s + n + "         Width           =   615";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CommandButton cmdPrint ";
        s = s + n + "         Caption         =   \"&Print\"";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   3120";
        s = s + n + "         TabIndex        =   62";
        s = s + n + "         Top             =   7800";
        s = s + n + "         Width           =   615";
        s = s + n + "      End";
        s = s + n + "      Begin VB.ComboBox cboCashOption ";
        s = s + n + "         Height          =   315";
        s = s + n + "         ItemData        =   \"ArPaySetUp.frx\":030A";
        s = s + n + "         Left            =   1800";
        s = s + n + "         List            =   \"ArPaySetUp.frx\":030C";
        s = s + n + "         Style           =   2  'Dropdown List";
        s = s + n + "         TabIndex        =   44";
        s = s + n + "         ToolTipText     =   \"Select the number of months to be Same As Cash.\"";
        s = s + n + "         Top             =   5880";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkAutoARNO ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Auto A/R No:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   420";
        s = s + n + "         TabIndex        =   9";
        s = s + n + "         Top             =   2520";
        s = s + n + "         Width           =   1275";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtBalDueLateCharge ";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   9.75";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   400";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   3360";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   22";
        s = s + n + "         Top             =   3360";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtAddlPaymentsMade ";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   9.75";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   400";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   3300";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   20";
        s = s + n + "         ToolTipText     =   \"Additional Payments Made.\"";
        s = s + n + "         Top             =   2760";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtPaymentWillBe ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"Arial\"";
        s = s + n + "            Size            =   12";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   700";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   405";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   54";
        s = s + n + "         Top             =   7320";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtRate ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   2880";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   41";
        s = s + n + "         ToolTipText     =   \"Interest Rate.\"";
        s = s + n + "         Top             =   5520";
        s = s + n + "         Width           =   615";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Frame fraLateChargesApplied ";
        s = s + n + "         Height          =   1275";
        s = s + n + "         Left            =   720";
        s = s + n + "         TabIndex        =   4";
        s = s + n + "         Top             =   1080";
        s = s + n + "         Width           =   3135";
        s = s + n + "         Begin VB.OptionButton optLate26 ";
        s = s + n + "            Caption         =   \"Due On The 20th.  Late on 26th\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   8";
        s = s + n + "            Top             =   900";
        s = s + n + "            Width           =   2655";
        s = s + n + "         End";
        s = s + n + "         Begin VB.OptionButton optLate16 ";
        s = s + n + "            Caption         =   \"Due On The 10th.  Late on 16th\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   7";
        s = s + n + "            Top             =   660";
        s = s + n + "            Width           =   2655";
        s = s + n + "         End";
        s = s + n + "         Begin VB.OptionButton optLate6 ";
        s = s + n + "            Caption         =   \"Due On The 1st.  Late on 6th\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   6";
        s = s + n + "            Top             =   420";
        s = s + n + "            Width           =   2655";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblLateChargesApplied ";
        s = s + n + "            Caption         =   \"Late Charges Will Be Applied:\"";
        s = s + n + "            BeginProperty Font ";
        s = s + n + "               Name            =   \"MS Sans Serif\"";
        s = s + n + "               Size            =   8.25";
        s = s + n + "               Charset         =   0";
        s = s + n + "               Weight          =   700";
        s = s + n + "               Underline       =   0   'False";
        s = s + n + "               Italic          =   0   'False";
        s = s + n + "               Strikethrough   =   0   'False";
        s = s + n + "            EndProperty";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   5";
        s = s + n + "            Top             =   180";
        s = s + n + "            Width           =   2655";
        s = s + n + "         End";
        s = s + n + "      End";
        s = s + n + "      Begin MSComCtl2.DTPicker dteDate1 ";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   360";
        s = s + n + "         TabIndex        =   0";
        s = s + n + "         Top             =   240";
        s = s + n + "         Width           =   1575";
        s = s + n + "         _ExtentX        =   2778";
        s = s + n + "         _ExtentY        =   661";
        s = s + n + "         _Version        =   393216";
        s = s + n + "         BeginProperty Font {0BE35203-8F91-11CE-9DE3-00AA004BB851} ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   9.75";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   400";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         CalendarTitleBackColor=   8454143";
        s = s + n + "         CustomFormat    =   \"MM/dd/yyyy\"";
        s = s + n + "         Format          =   121569283";
        s = s + n + "         CurrentDate     =   36893";
        s = s + n + "      End";
        s = s + n + "      Begin MSComCtl2.DTPicker dteDate2 ";
        s = s + n + "         Height          =   375";
        s = s + n + "         Left            =   360";
        s = s + n + "         TabIndex        =   2";
        s = s + n + "         Top             =   600";
        s = s + n + "         Width           =   1575";
        s = s + n + "         _ExtentX        =   2778";
        s = s + n + "         _ExtentY        =   661";
        s = s + n + "         _Version        =   393216";
        s = s + n + "         BeginProperty Font {0BE35203-8F91-11CE-9DE3-00AA004BB851} ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   9.75";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   400";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         CalendarTitleBackColor=   8454143";
        s = s + n + "         CustomFormat    =   \"MM/dd/yyyy\"";
        s = s + n + "         Format          =   121569283";
        s = s + n + "         CurrentDate     =   36894";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtFinanceChargeSalesTax ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         Locked          =   -1  'True";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   50";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   6720";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtFinanceCharges ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   48";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   6480";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtDeferredInt ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         Locked          =   -1  'True";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   46";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   6240";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.ComboBox cboDeferred ";
        s = s + n + "         Height          =   315";
        s = s + n + "         ItemData        =   \"ArPaySetUp.frx\":030E";
        s = s + n + "         Left            =   2880";
        s = s + n + "         List            =   \"ArPaySetUp.frx\":0310";
        s = s + n + "         Style           =   2  'Dropdown List";
        s = s + n + "         TabIndex        =   65";
        s = s + n + "         ToolTipText     =   \"Select the number of months to be Same As Cash.\"";
        s = s + n + "         Top             =   5880";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtFinanceAmount ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   40";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   5640";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtMonthsToFinance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   5";
        s = s + n + "         TabIndex        =   38";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   5400";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkProperty ";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2820";
        s = s + n + "         TabIndex        =   33";
        s = s + n + "         Top             =   4680";
        s = s + n + "         Width           =   255";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtPropertyInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   32";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   4680";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkAccident ";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2820";
        s = s + n + "         TabIndex        =   30";
        s = s + n + "         Top             =   4440";
        s = s + n + "         Width           =   255";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtAccidentInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   29";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   4440";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.CheckBox chkLife ";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2820";
        s = s + n + "         TabIndex        =   27";
        s = s + n + "         Top             =   4200";
        s = s + n + "         Width           =   255";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtLifeInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   26";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   4200";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtDocFee ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   24";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   3960";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtSubTotal ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         Locked          =   -1  'True";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   18";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   3480";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtOrigDeposit ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   16";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   3240";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtGrossSale ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   14";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   3000";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtPrevBalance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   10";
        s = s + n + "         TabIndex        =   12";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   2760";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.TextBox txtArNo ";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   1800";
        s = s + n + "         MaxLength       =   50";
        s = s + n + "         TabIndex        =   10";
        s = s + n + "         Text            =   \" \"";
        s = s + n + "         Top             =   2520";
        s = s + n + "         Width           =   975";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Frame fraMath ";
        s = s + n + "         Height          =   1695";
        s = s + n + "         Left            =   3000";
        s = s + n + "         TabIndex        =   71";
        s = s + n + "         Top             =   6840";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   1455";
        s = s + n + "         Begin VB.Label lblMathTotal ";
        s = s + n + "            Alignment       =   1  'Right Justify";
        s = s + n + "            Caption         =   \"$5999.38\"";
        s = s + n + "            Height          =   230";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   78";
        s = s + n + "            Top             =   1440";
        s = s + n + "            Width           =   975";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathLastPay ";
        s = s + n + "            Alignment       =   1  'Right Justify";
        s = s + n + "            Caption         =   \"$499.38\"";
        s = s + n + "            Height          =   240";
        s = s + n + "            Left            =   360";
        s = s + n + "            TabIndex        =   77";
        s = s + n + "            Top             =   1080";
        s = s + n + "            Width           =   855";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Line linSum2 ";
        s = s + n + "            X1              =   120";
        s = s + n + "            X2              =   1320";
        s = s + n + "            Y1              =   1320";
        s = s + n + "            Y2              =   1320";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathAdd ";
        s = s + n + "            AutoSize        =   -1  'True";
        s = s + n + "            Caption         =   \"+\"";
        s = s + n + "            Height          =   195";
        s = s + n + "            Left            =   225";
        s = s + n + "            TabIndex        =   76";
        s = s + n + "            Top             =   1080";
        s = s + n + "            Width           =   90";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathMonthlyTotal ";
        s = s + n + "            Alignment       =   1  'Right Justify";
        s = s + n + "            Caption         =   \"$5500.00\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   75";
        s = s + n + "            Top             =   840";
        s = s + n + "            Width           =   975";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathMontlyMonths ";
        s = s + n + "            Alignment       =   1  'Right Justify";
        s = s + n + "            Caption         =   \"11\"";
        s = s + n + "            Height          =   240";
        s = s + n + "            Left            =   480";
        s = s + n + "            TabIndex        =   74";
        s = s + n + "            Top             =   480";
        s = s + n + "            Width           =   735";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Line linSum ";
        s = s + n + "            X1              =   120";
        s = s + n + "            X2              =   1320";
        s = s + n + "            Y1              =   720";
        s = s + n + "            Y2              =   720";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathMultiply ";
        s = s + n + "            AutoSize        =   -1  'True";
        s = s + n + "            Caption         =   \"x\"";
        s = s + n + "            Height          =   195";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   73";
        s = s + n + "            Top             =   480";
        s = s + n + "            Width           =   75";
        s = s + n + "         End";
        s = s + n + "         Begin VB.Label lblMathMonthly ";
        s = s + n + "            Alignment       =   1  'Right Justify";
        s = s + n + "            Caption         =   \"$500.00\"";
        s = s + n + "            Height          =   255";
        s = s + n + "            Left            =   240";
        s = s + n + "            TabIndex        =   72";
        s = s + n + "            Top             =   240";
        s = s + n + "            Width           =   975";
        s = s + n + "         End";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Frame fraCoupons ";
        s = s + n + "         Height          =   732";
        s = s + n + "         Left            =   2880";
        s = s + n + "         TabIndex        =   61";
        s = s + n + "         Top             =   6120";
        s = s + n + "         Width           =   1632";
        s = s + n + "         Begin VB.OptionButton optWeekly ";
        s = s + n + "            Caption         =   \"&Weekly Coupons\"";
        s = s + n + "            Height          =   192";
        s = s + n + "            Left            =   60";
        s = s + n + "            TabIndex        =   60";
        s = s + n + "            Top             =   420";
        s = s + n + "            Width           =   1512";
        s = s + n + "         End";
        s = s + n + "         Begin VB.OptionButton optMonthly ";
        s = s + n + "            Caption         =   \"&Monthly Coupons\"";
        s = s + n + "            Height          =   192";
        s = s + n + "            Left            =   60";
        s = s + n + "            TabIndex        =   59";
        s = s + n + "            Top             =   180";
        s = s + n + "            Value           =   -1  'True";
        s = s + n + "            Width           =   1550";
        s = s + n + "         End";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblTotalCaption ";
        s = s + n + "         AutoSize        =   -1  'True";
        s = s + n + "         Caption         =   \"Total:\"";
        s = s + n + "         Height          =   195";
        s = s + n + "         Left            =   2880";
        s = s + n + "         TabIndex        =   81";
        s = s + n + "         Top             =   3840";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   405";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblTotal ";
        s = s + n + "         Appearance      =   0  'Flat";
        s = s + n + "         BackColor       =   &H80000005&";
        s = s + n + "         BorderStyle     =   1  'Fixed Single";
        s = s + n + "         ForeColor       =   &H80000008&";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   3360";
        s = s + n + "         TabIndex        =   80";
        s = s + n + "         Top             =   3840";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   855";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblUnemploymentInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Unempl. Insurance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   120";
        s = s + n + "         TabIndex        =   34";
        s = s + n + "         Top             =   4920";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   1575";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblTotalBalance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Total Balance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   51";
        s = s + n + "         Top             =   6960";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblFinanceChargeSalesTax ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Sales Tax:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   49";
        s = s + n + "         Top             =   6720";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblAPR ";
        s = s + n + "         Appearance      =   0  'Flat";
        s = s + n + "         BorderStyle     =   1  'Fixed Single";
        s = s + n + "         ForeColor       =   &H80000008&";
        s = s + n + "         Height          =   285";
        s = s + n + "         Left            =   3600";
        s = s + n + "         TabIndex        =   42";
        s = s + n + "         ToolTipText     =   \"APR\"";
        s = s + n + "         Top             =   5520";
        s = s + n + "         Width           =   495";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblSubTotal ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Sub Total:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   480";
        s = s + n + "         TabIndex        =   17";
        s = s + n + "         Top             =   3480";
        s = s + n + "         Width           =   1215";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblCashOpt ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Cash Option:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   480";
        s = s + n + "         TabIndex        =   43";
        s = s + n + "         Top             =   5880";
        s = s + n + "         Width           =   1200";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblDeferredInt ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Deferment Interest:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   45";
        s = s + n + "         Top             =   6240";
        s = s + n + "         Visible         =   0   'False";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblDeferred ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Pay Def\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   3000";
        s = s + n + "         TabIndex        =   58";
        s = s + n + "         Top             =   5920";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblFirstPaymentDue ";
        s = s + n + "         Caption         =   \"First Payment Due\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2040";
        s = s + n + "         TabIndex        =   3";
        s = s + n + "         Top             =   720";
        s = s + n + "         Width           =   1335";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblDelDate ";
        s = s + n + "         Caption         =   \"Delivery Date\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   2040";
        s = s + n + "         TabIndex        =   1";
        s = s + n + "         Top             =   360";
        s = s + n + "         Width           =   1335";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblAcctNo ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Account No:\"";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   8.25";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   700";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   195";
        s = s + n + "         Left            =   480";
        s = s + n + "         TabIndex        =   66";
        s = s + n + "         Top             =   8160";
        s = s + n + "         Width           =   1155";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblAccountNo ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   9.75";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   700";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   1800";
        s = s + n + "         TabIndex        =   67";
        s = s + n + "         Top             =   8160";
        s = s + n + "         Width           =   915";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblBalDueLateCharge ";
        s = s + n + "         Caption         =   \"Bal Due Late Chg:\"";
        s = s + n + "         Height          =   195";
        s = s + n + "         Left            =   2880";
        s = s + n + "         TabIndex        =   21";
        s = s + n + "         Top             =   3120";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblAddlPayments ";
        s = s + n + "         Caption         =   \"Additional Pmts Made:\"";
        s = s + n + "         Height          =   195";
        s = s + n + "         Left            =   2880";
        s = s + n + "         TabIndex        =   19";
        s = s + n + "         ToolTipText     =   \"Additional Payments Made.\"";
        s = s + n + "         Top             =   2520";
        s = s + n + "         Width           =   1635";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblContract ";
        s = s + n + "         Alignment       =   2  'Center";
        s = s + n + "         Caption         =   \"Contract \"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   3120";
        s = s + n + "         TabIndex        =   69";
        s = s + n + "         Top             =   7560";
        s = s + n + "         Width           =   1215";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblPrevBal ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Previous Balance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   11";
        s = s + n + "         Top             =   2760";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblPaymentWillBe ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Payment Will Be:\"";
        s = s + n + "         BeginProperty Font ";
        s = s + n + "            Name            =   \"MS Sans Serif\"";
        s = s + n + "            Size            =   8.25";
        s = s + n + "            Charset         =   0";
        s = s + n + "            Weight          =   700";
        s = s + n + "            Underline       =   0   'False";
        s = s + n + "            Italic          =   0   'False";
        s = s + n + "            Strikethrough   =   0   'False";
        s = s + n + "         EndProperty";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   53";
        s = s + n + "         Top             =   7320";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblPropertyInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Property Insurance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   31";
        s = s + n + "         Top             =   4680";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblAccidentInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Accident Insurance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   28";
        s = s + n + "         Top             =   4440";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblLifeInsurance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Life Insurance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   25";
        s = s + n + "         Top             =   4200";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblDocFee ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Documentation Fee:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   23";
        s = s + n + "         Top             =   3960";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblFinanceCharges ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Finance Charges:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   47";
        s = s + n + "         Top             =   6480";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblMonthsToFinance ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Months To Finance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   37";
        s = s + n + "         Top             =   5400";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblFinanceAmount ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Amount To Finance:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   39";
        s = s + n + "         Top             =   5640";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblOrigDeposit ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Original Deposit:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   15";
        s = s + n + "         Top             =   3240";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "      Begin VB.Label lblGrossSale ";
        s = s + n + "         Alignment       =   1  'Right Justify";
        s = s + n + "         Caption         =   \"Gross Sale W/Tax:\"";
        s = s + n + "         Height          =   255";
        s = s + n + "         Left            =   240";
        s = s + n + "         TabIndex        =   13";
        s = s + n + "         Top             =   3000";
        s = s + n + "         Width           =   1455";
        s = s + n + "      End";
        s = s + n + "   End";
        s = s + n + "End";
        s = s + n + "Attribute VB_Name = \"ARPaySetUp\"";
        s = s + n + "Attribute VB_GlobalNameSpace = False";
        s = s + n + "Attribute VB_Creatable = False";
        s = s + n + "Attribute VB_PredeclaredId = True";
        s = s + n + "Attribute VB_Exposed = False";
        s = s + n + "";

        var testCaseFrm2 = s;
        return testCaseFrm2;
    }

    public static string TestCaseFunc()
    {
        var r = "";
        var n = vbCrLf;
        var m = "";

        r = r + m + "Private Function AlreadyMadeSameAsCash() As Boolean";
        //  R = R & N & "  Dim R As Recordset"
        //  R = R & N & "  Set R = GetRecordsetBySQL(""SELECT * FROM [Transactions] WHERE [ArNo]="""""" & ProtectSQL(ArNo) & """""" ORDER BY [TransDate] ASC, [TransactionID] ASC"", , GetDatabaseAtLocation())"
        r = r + n + "  Do While Not R.EOF";
        //  R = R & N & "    If LCase(Left(R(""Type""), 7)) = LCase(arPT_New) Then AlreadyMadeSameAsCash = False"
        //  R = R & N & "    If LCase(Left(R(""Receipt""), 12)) = ""same as cash"" Then AlreadyMadeSameAsCash = True"
        r = r + n + "    R.MoveNext";
        r = r + n + "  Loop";
        r = r + n + "  DisposeDA R";
        r = r + n + "End Function";

        var testCaseFunc = r;
        return testCaseFunc;
    }
}