namespace Vb6ToCSharp;

public static class VbConstants
{
    public const int VbKeyLButton = 1; // Left mouse button
    public const int VbKeyRButton = 2;  // CANCEL mouse button 
    public const int VbKeyCancel = 3;  // Middle key  
    public const int VbKeyMButton = 4;  // BACKSPACE mouse button 
    public const int VbKeyBack = 8;  // TAB key  
    public const int VbKeyTab = 9;  //  key  
    public const int VbKeyClear = 12;  //  CLEAR key 
    public const int VbKeyReturn = 13;  //  ENTER key 
    public const int VbKeyShift = 16;  //  SHIFT key 
    public const int VbKeyControl = 17;  //  CTRL key 
    public const int VbKeyMenu = 18;  //  MENU key 
    public const int VbKeyPause = 19;  //  PAUSE key 
    public const int VbKeyCapital = 20;  //  CAPS lock key
    public const int VbKeyEscape = 27;  //  ESC key 
    public const int VbKeySpace = 32;  //  SPACEBAR key 
    public const int VbKeyPageUp = 33;  //  PAGE UP key
    public const int VbKeyPageDown = 34;  //  PAGE DOWN key
    public const int VbKeyEnd = 35;  //  END key 
    public const int VbKeyHome = 36;  //  HOME key 
    public const int VbKeyLeft = 37;  //  LEFT ARROW key
    public const int VbKeyUp = 38;  //  UP ARROW key
    public const int VbKeyRight = 39;  //  RIGHT ARROW key
    public const int VbKeyDown = 40;  //  DOWN ARROW key
    public const int VbKeySelect = 41;  //  SELECT key 
    public const int VbKeyPrint = 42;  //  print SCREEN key
    public const int VbKeyExecute = 43;  //  EXECUTE key 
    public const int VbKeySnapshot = 44;  //  SNAPSHOT key 
    public const int VbKeyInsert = 45;  //  INS key 
    public const int VbKeyDelete = 46;  //  DEL key 
    public const int VbKeyHelp = 47;  // NUM HELP key 
    public const int VbKeyNumlock = 144;  //  lock key 
    public const int VbKeyA = 65;  //  A key 
    public const int VbKeyB = 66;  //  B key 
    public const int VbKeyC = 67;  //  C key 
    public const int VbKeyD = 68;  //  D key 
    public const int VbKeyE = 69;  //  E key 
    public const int VbKeyF = 70;  //  F key 
    public const int VbKeyG = 71;  //  G key 
    public const int VbKeyH = 72;  //  H key 
    public const int VbKeyI = 73;  //  I key 
    public const int VbKeyJ = 74;  //  J key 
    public const int VbKeyK = 75;  //  K key 
    public const int VbKeyL = 76;  //  L key 
    public const int VbKeyM = 77;  //  M key 
    public const int VbKeyN = 78;  //  N key 
    public const int VbKeyO = 79;  //  O key 
    public const int VbKeyP = 80;  //  P key 
    public const int VbKeyQ = 81;  //  Q key 
    public const int VbKeyR = 82;  //  R key 
    public const int VbKeyS = 83;  //  S key 
    public const int VbKeyT = 84;  //  T key 
    public const int VbKeyU = 85;  //  U key 
    public const int VbKeyV = 86;  //  V key 
    public const int VbKeyW = 87;  //  W key 
    public const int VbKeyX = 88;  //  X key 
    public const int VbKeyY = 89;  //  Y key 
    public const int VbKeyZ = 90;  //  Z key 
    public const int VbKey0 = 48;  //  0 key 
    public const int VbKey1 = 49;  //  1 key 
    public const int VbKey2 = 50;  //  2 key 
    public const int VbKey3 = 51;  //  3 key 
    public const int VbKey4 = 52;  //  4 key 
    public const int VbKey5 = 53;  //  5 key 
    public const int VbKey6 = 54;  //  6 key 
    public const int VbKey7 = 55;  //  7 key 
    public const int VbKey8 = 56;  //  8 key 
    public const int VbKey9 = 57;  //  9 key 
    public const int VbKeyNumpad0 = 96;  //  0 key 
    public const int VbKeyNumpad1 = 97;  //  1 key 
    public const int VbKeyNumpad2 = 98;  //  2 key 
    public const int VbKeyNumpad3 = 99;  // 4 3 key 
    public const int VbKeyNumpad4 = 100;  // 5 key  
    public const int VbKeyNumpad5 = 101;  // 6 key  
    public const int VbKeyNumpad6 = 102;  // 7 key  
    public const int VbKeyNumpad7 = 103;  // 8 key  
    public const int VbKeyNumpad8 = 104;  // 9 key  
    public const int VbKeyNumpad9 = 105;  // MULTIPLICATION key  
    public const int VbKeyMultiply = 106;  // PLUS SIGN (*) key
    public const int VbKeyAdd = 107;  // ENTER SIGN (+) key
    public const int VbKeySeparator = 108;  // MINUS (keypad) key 
    public const int VbKeySubtract = 109;  // DECIMAL SIGN (-) key
    public const int VbKeyDecimal = 110;  // DIVISION POINT(.) key 
    public const int VbKeyDivide = 111;  // F1 SIGN (/) key
    public const int VbKeyF1 = 112;  // F2 key  
    public const int VbKeyF2 = 113;  // F3 key  
    public const int VbKeyF3 = 114;  // F4 key  
    public const int VbKeyF4 = 115;  // F5 key  
    public const int VbKeyF5 = 116;  // F6 key  
    public const int VbKeyF6 = 117;  // F7 key  
    public const int VbKeyF7 = 118;  // F8 key  
    public const int VbKeyF8 = 119;  // F9 key  
    public const int VbKeyF9 = 120;  // F10 key  
    public const int VbKeyF10 = 121;  // F11 key  
    public const int VbKeyF11 = 122;  // F12 key  
    public const int VbKeyF12 = 123;  // F13 key  
    public const int VbKeyF13 = 124;  // F14 key  
    public const int VbKeyF14 = 125;  // F15 key  
    public const int VbKeyF15 = 126;  // F16 key  
    public const int VbKeyF16 = 127;  //  key  
    public const int VbBlack = 0x0;  // BLACK
    public const int VbBlue = 0x0000FF;  // BLUE
    public const int VbCyan = 0x00FFFF;  // CYAN
    public const int VbGreen = 0x00FF00;  // GREEN
    public const int VbMagenta = 0xFFFF00;  // MAGENTA
    public const int VbRed = 0xFF0000;  // RED
    public const int VbWhite = 0xFFFFFF;  // WHITE
    public const int VbYellow = 0xFF00FF;  // YELLOW
    public const int VbModal = 0x1;
    public enum AlignConstants { VbAlignNone = 0, VbAlignTop = 1, VbAlignBottom = 2, VbAlignLeft = 3, VbAlignRight = 4, VbLeftJustify = 5, VbRightJustify = 6, VbCenter = 7 }
    public enum AlignmentConstants : byte { VbLeftJustify = 0, VbRightJustify = 1, VbCenter = 2 }

    // Cursors
    public const int VbDefault = 0;
    public const int VbArrow = 1;
    public const int VbHourglass = 11;

    public const int FlexAlignLeftCenter = 0;
    public const int FlexAlignRightCenter = 0;
    public const int FlexAlignCenterCenter = 0;
}